MACRO(BASICCONFIGURATION)
    # set project name
    SET(PrjName Noises)

    # define libraries
    SET(PrjLibraries 
        base
        simplenoise)

    # define executables
    SET(PrjExecutables 
        noises)
ENDMACRO(BASICCONFIGURATION)

MACRO(INITIALIZEEXTERNAL)
    # INIT AND COLLECT DEPENDENCIES
    INITDEPENDENCIES()
    CHECKQT5DIRSET()
    WHICHVS()
    COLLECTDEPINCLUDES()
    COLLECTDEPLIBS()
ENDMACRO(INITIALIZEEXTERNAL)

MACRO(DEFINEMODULEQTDEPENDENCY)
    SETMODULEQTTARGETSLIST(noises Core Widgets Gui)
ENDMACRO(DEFINEMODULEQTDEPENDENCY)

MACRO(DEFINEMODULELINKDEPENDENCY)
    SETMODULELINKTARGETSLIST(noises base)
    SETMODULELINKTARGETSLIST(simplenoise base)
ENDMACRO(DEFINEMODULELINKDEPENDENCY)

MACRO(DEFINEEXTERNALINCLUDEDEPENDENCIES)
    # external includes are going here
ENDMACRO(DEFINEEXTERNALINCLUDEDEPENDENCIES)

MACRO(DEFINEEXTERNALLINKDEPENDENCIES)
    # external link are going here
ENDMACRO(DEFINEEXTERNALLINKDEPENDENCIES)

MACRO(DEFINEDEFINES)

ENDMACRO(DEFINEDEFINES)