MACRO(CHECKQT5DIRSET)
    # set qt dir here
    IF("${QT5_PATH}" STREQUAL "")
        SET(QT5_PATH $ENV{QTDIR})
    ENDIF("${QT5_PATH}" STREQUAL "")
    
    IF("${QT5_PATH}" STREQUAL "")
        MESSAGE(FATAL_ERROR "QT5 Dir not set")
    ENDIF("${QT5_PATH}" STREQUAL "")
ENDMACRO(CHECKQT5DIRSET)

MACRO(WHICHVS)

ENDMACRO(WHICHVS)

MACRO(INITDEPENDENCIES)
    
ENDMACRO(INITDEPENDENCIES)

MACRO(COLLECTDEPINCLUDES)
    
ENDMACRO(COLLECTDEPINCLUDES)

MACRO(COLLECTDEPLIBS)
    
ENDMACRO(COLLECTDEPLIBS)

FUNCTION(COLLECTDEPBINS dbg_bins rel_bins)
    
ENDFUNCTION(COLLECTDEPBINS dbg_bins rel_bins)